name: gilang
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ^3.7.0

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8
    url_launcher: ^6.2.5
    device_preview: ^1.1.0
    http: ^1.4.0
    shared_preferences: ^2.5.3
    get: ^4.7.2
    intl: ^0.19.0
    flutter_launcher_icons: ^0.14.4

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0

flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/Tribun_media.png"

flutter:
    uses-material-design: true
    assets:
        - assets/Tribun_media.png
